enabled_modules:
- modules.Daisy
- modules.TtsElevenLabs
- modules.GoogleScraper
- modules.Calculator

keys:
  assembly_ai: 90d30f97a11249c7849315557631c4d6
  openai: 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
  serp_api: 2b225c107a1f84c12a941af91e28d4213594c995b63899e081c3d782051dd2c3
  elevenlabs: bce46cacedc379a807e964ef163d9f8a
  porcupine: QTQ28lQFSW2Fdw+FvEtFcTDkRz7+jJepnQ1Bmm+oB164gmfJJlO34A==

hardware:
  input_device_index: 1
  led: False